import backoff
from openai import RateLimitError, APIConnectionError, InternalServerError, APITimeoutError
from .openai_utils import OutOfQuotaException, AccessTerminatedException
from .config import build_openai_client

support_models = ['gpt-3.5-turbo', 'gpt-3.5-turbo-0301', 'gpt-4o-mini', 'gpt-4.1-mini', 'qwen2.5-72b-instruct', 'Llama-3.1-70B-Instruct', 'gemini-3.5-flash', 'google/gemini-3.5-flash', 'claude-haiku-4-5']

class Agent:
    """LLM とのチャット履歴を保持し、問い合わせを行う基底エージェント。

    memory_lst に system / user / assistant ロールの履歴を積み、set_meta_prompt /
    add_event / add_memory で構築して ask()（内部で query()）が LLM を呼ぶ。API 呼び出しは
    backoff により RateLimit/APIError 等を指数バックオフでリトライする。

    Attributes:
        model_name (str): 使用モデル名。
        name (str): エージェント名（履歴表示・save_file のキーに使用）。
        temperature (float): サンプリング温度。
        memory_lst (list[dict]): チャット履歴（role/content の辞書のリスト）。
        sleep_time (float): レート制限対策のスリープ秒。
    """

    def __init__(self, model_name: str, name: str, temperature: float, sleep_time: float=0) -> None:
        """Create an agent

        Args:
            model_name(str): model name
            name (str): name of this agent
            temperature (float): higher values make the output more random, while lower values make it more focused and deterministic
            sleep_time (float): sleep because of rate limits
        """
        self.model_name = model_name
        self.name = name
        self.temperature = temperature
        self.memory_lst = []
        self.sleep_time = sleep_time

    # リトライは一時的エラー（429 / 接続断 / タイムアウト / 5xx）のみ。4xx の恒久エラー
    # （BadRequest / Authentication 等）は即時に呼び出し元へ伝播し、_eval_dimension /
    # _run_judge が api_failures に記録して success:false に落とす（Issue #52/#58）。
    @backoff.on_exception(backoff.expo, (RateLimitError, APIConnectionError, InternalServerError, APITimeoutError), max_tries=20)
    def query(self, messages: "list[dict]", api_key: str, temperature: float) -> str:
        """make a query

        Args:
            messages (list[dict]): chat history in turbo format
            api_key (str): openai api key
            temperature (float): sampling temperature

        Raises:
            OutOfQuotaException: the apikey has out of quota
            AccessTerminatedException: the apikey has been ban

        Returns:
            str: the return msg
        """
        # time.sleep(self.sleep_time)
        # プロバイダ設定（OpenAI / Gemini）から client と使用モデルを解決する。
        client, model = build_openai_client(fallback_api_key=api_key)
        assert model in support_models, f"Not support {model}. Choices: {support_models}"
        try:
            response = client.chat.completions.create(
                model=model,
                messages=messages,
                temperature=temperature,
                # 応答トークン上限。gemini の thinking はこの枠を消費するため、1000 だと
                # 長い入力で枠を使い切り finish_reason=MAX_TOKENS の空応答（message=None）に
                # なり success:false を招いていた（#64）。8192 に拡大して本文出力の余地を確保。
                # 出力は短い JSON のため他プロバイダの実害・コスト増はない（キャップは上限）。
                max_tokens=8192,
            )
            gen = response.choices[0].message.content
            return gen

        except RateLimitError as e:
            message = str(e)
            if "You exceeded your current quota, please check your plan and billing details" in message:
                raise OutOfQuotaException(api_key)
            elif "Your access was terminated due to violation of our policies" in message:
                raise AccessTerminatedException(api_key)
            else:
                raise e

    def set_meta_prompt(self, meta_prompt: str):
        """Set the meta_prompt

        Args:
            meta_prompt (str): the meta prompt
        """
        self.memory_lst.append({"role": "system", "content": f"{meta_prompt}"})

    def add_event(self, event: str):
        """Add an new event in the memory

        Args:
            event (str): string that describe the event.
        """
        self.memory_lst.append({"role": "user", "content": f"{event}"})

    def add_memory(self, memory: str):
        """Monologue in the memory

        Args:
            memory (str): string that generated by the model in the last round.
        """
        self.memory_lst.append({"role": "assistant", "content": f"{memory}"})
        print(f"----- {self.name} -----\n{memory}\n")

    def ask(self, temperature: float=None):
        """Query for answer

        Args:
        """
        print(self.memory_lst)
        return self.query(self.memory_lst, api_key=self.openai_api_key, temperature=temperature if temperature else self.temperature)

